accounts/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.RegisterView.as_view(), name='register')
]

quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.QuoteList.as_view(), name='index'),
    path('<int:pk>/', views.QuoteDetail.as_view(), name='detail'),
    path('new/', views.SubmitQuote.as_view(), name='create'),
]

urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quotes/', include('quotes.urls', namespace='quotes')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

quotes/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.utils.functional import cached_property

class Quote(models.Model):
    submitter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='submitter_user',
        blank=True,
        null=True
    )
    approver = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        limit_choices_to={'is_staff': True},
        related_name='approver_user',
        blank=True,
        null=True
    )
    pub_date = models.DateTimeField(
        'Occurence date',
        default=timezone.now,
        help_text='The date and time that this quote or conversation occured.'
    )
    content = models.TextField(max_length=1000)
    is_published = models.BooleanField(
        'Published status',
        default=False,
        help_text='Quote is approved and published on the site.'
    )

    def __str__(self):
        return f"#{self.pk}"

    def get_absolute_url(self):
        return reverse('quotes:detail', kwargs={'pk': self.pk})

    @cached_property
    def lines(self):
        return self.content.split('\n')

    class Meta:
        ordering = ['-pub_date']

accounts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters

from django.views.generic import CreateView

class RegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('quotes:index')

    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def dispatch(self, request, *args, **kwargs):
        """Disallow registered users from registering another account"""
        if request.user.is_authenticated:
            # TODO: Make this redirect to their user profile
            return redirect('/')

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """Log in user after registering"""
        valid_form = super().form_valid(form)
        login(self.request, form.instance)

        return valid_form

quotes/views.py
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView

from .models import Quote


class QuoteList(ListView):
    paginate_by = 10
    context_object_name = 'quotes'

    def get_queryset(self):
        if self.request.user.is_staff:
            return Quote.objects.all()
        else:
            return Quote.objects.filter(is_published=True)


class QuoteDetail(DetailView):
    model = Quote

    def get_object(self, queryset=None):
        quote = super().get_object()

        if quote.is_published or quote.submitter is self.request.user or self.request.user.is_staff:
            return quote
        else:
            raise PermissionDenied('User lacks permission to view requested quote')


class SubmitQuote(SuccessMessageMixin, CreateView):
    model = Quote
    fields = ['content']

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.submitter = self.request.user

        # Automatically publish submissions made by staff
        if self.request.user.is_staff:
            form.instance.approver = self.request.user
            form.instance.is_published = True

        return super().form_valid(form)

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return self.object.get_absolute_url()
        else:
            return reverse('quotes:index')

    def get_success_message(self, cleaned_data):
        if self.request.user.is_staff:
            return 'Quote successfully added.'
        else:
            return '''Your quote was successfully submitted. It is
    currently under moderator review.'''

quotes/templates/quotes/quote_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-8">
      <h3>Quote #{{ quote.pk }}</h3>
      <ul class="list-group">
        {% for line in quote.lines %}
          <li class="list-group-item {% cycle '' 'list-group-item-secondary' %}">
            {{ line }}
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-4">
      <h3>Information</h3>

      <h4>Meta</h4>
      <p>This quote was submitted by {{ quote.submitter }} on {{ quote.pub_date }}</p>

      <h4>Score</h4>

      <h4>Stats</h4>

      {% if user.is_staff %}
        <h4>Administrate</h4>
      {% endif %}
    </div>
  </div>
{% endblock %}

quotes/templates/quotes/quote_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <h2>Submit Quote</h2>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button 'Submit' button_type='submit' button_class='btn-primary' %}
  </form>
{% endblock %}

quotes/templates/quotes/quote_list.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  {% if quotes %}
    {% for quote in quotes %}
    <div class="card mb-3">
      <div class="card-body">
        {{ quote.content|linebreaks|escape }}
        <a href="{% url 'quotes:detail' quote.pk %}" class="card-link">Permalink</a>
      </div>
    </div>
    {% endfor %}

    {% bootstrap_pagination page_obj %}

    {% else %}
    <p>There's no quotes yet. Why don't you <a href="{% url 'quotes:create' %}">add one?</a></p>
  {% endif %}
{% endblock %}

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title>Quotezone</title>
    <meta charset="utf-8" />
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Quotezone</a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'quotes:index' %}">Recent</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Top</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Stats</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'quotes:create' %}">Submit</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarUserDropdown" role="button" data-toggle="dropdown">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarUserDropdown">
              {% if user.is_staff %}
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">
              Log in
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>

    <div class="container mt-3">
      {% bootstrap_messages %}

      <main id="content">
        {% block content %}
        {% endblock %}
      </main>

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            Quotezone knows all.
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>